desafioPratico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # Django Admin
    path("admin/", admin.site.urls),
    # User Management
    path("accounts/", include("allauth.urls")),
    # Local
    path("", include("pages.urls", namespace="pages")),
    path("", include('orderapi.urls')),
]

orderapi/urls.py
# from django.conf.urls import url
from . import views
from django.urls import path, include

urlpatterns = [
    path('orders/', views.OrderList.as_view(), name='order-list'),
    path('orders/delete/<int:pk>/', views.OrderDeleteList.as_view(), name='order-delete'),
    path('orders/update/<int:pk>/', views.OrderRetriveUpdateList.as_view(), name='order-update')
]

pages/urls.py
from django.urls import path

from . import views

app_name = "pages"

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home"),
]

orderapi/models.py
from django.db import models

from django.conf import settings
from sympy import product
from users.models import User

from django.contrib import auth
import datetime

AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')

# Create your models here.

class Order(models.Model):

    owner = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    resquest_date = models.DateField(default=datetime.date.today)
    product = models.TextField()
    quantity = models.IntegerField()

    class Meta:
        db_table = 'order'

    def __str__(self):
        return str(self.quantity) + " " + self.product + " ordered by " + self.owner.username

pages/models.py
from django.db import models

# Create your models here.

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    email = models.EmailField(blank=True, null=True)
    birth_date = models.DateField(blank=False, null=False, default='1999-01-01')
    
    def __str__(self) -> str:
        return super().username

users/forms.py
from django.contrib.auth import forms
from django import forms as d_forms

from .models import User

from allauth.account.forms import SignupForm
from allauth.account.forms import PasswordField

import string
from random import randint

class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):
    class Meta(forms.UserCreationForm.Meta):
        model = User

def createPassword():
    letters = list(string.ascii_lowercase)
    p = ''

    for i in range(4):
        p += letters[randint(0, len(letters)-1)]

    for i in range(4):
        p += str(randint(0, 9))

    return p

class UserSignupForm(SignupForm):
    # birth_date = d_forms.DateField(widget=d_forms.DateInput)
    birth_date = d_forms.DateField(widget=d_forms.DateInput(format='%d/%m/%Y', attrs={'data-mask':"00/00/0000"})) #widget=d_forms.widgets.DateInput(format='%Y-%m-%d')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["password1"] = PasswordField(
            label=("Password"), autocomplete="new-password", required=False
        )

        self.fields.pop('email')

    def save(self, request):

        # Ensure you call the parent class's save.
        # .save() returns a User object.
        user = super(UserSignupForm, self).save(request)

        # Add your own processing here.

        user.birth_date = self.cleaned_data["birth_date"]

        if self.cleaned_data["password1"] in ["", " "]:
            user.password = createPassword()
            print("\n\n senha :", user.password)

        user.save()

        # You must return the original result.
        return user

orderapi/views.py
from gc import get_objects
from urllib import request
from django.shortcuts import render
from numpy import delete
from rest_framework import generics
from .models import Order
from .serializers import OrderSerializer

# for get method overide
from rest_framework import status
from rest_framework.response import Response
from rest_framework.mixins import CreateModelMixin

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.http import Http404


class OrderDeleteList(generics.RetrieveDestroyAPIView):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        aux = super().get(request, *args, **kwargs)

        print('\n\naux:', aux.data)

        if not aux.data['owner'] == request.user.username:
            raise Http404

        return aux

    @method_decorator(login_required)
    def delete(self, request, *args, **kwargs):
        to_delete = Order.objects.get(self.kwargs['pk'])

        if to_delete.owner == request.user.name or request.user.is_staff:
            return super().delete(request, *args, **kwargs)
        
        return Response(status=status.HTTP_204_NO_CONTENT)

class OrderRetriveUpdateList(generics.RetrieveUpdateAPIView):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        aux = super().get(request, *args, **kwargs)

        print('\n\naux:', aux.data)

        if not aux.data['owner'] == request.user.username:
            raise Http404

        return aux
    
    @method_decorator(login_required)
    def put(self, request, *args, **kwargs):
        return super().put(request, *args, **kwargs)

    @method_decorator(login_required)
    def patch(self, request, *args, **kwargs):
        return super().patch(request, *args, **kwargs)

class OrderList(generics.ListCreateAPIView):
    queryset = Order.objects.all()
    serializer_class = OrderSerializer

    @method_decorator(login_required)
    def get(self, request, *args, **kwargs):
        x = Order.objects.all()
        print("\n\nid:", x[0].id)

        orders = []

        if not request.user.is_staff:
            orders = [x for x in Order.objects.all() if x.owner == request.user]

        else:
            orders = Order.objects.all()

        serializer = OrderSerializer(orders, many=True)

        return Response(serializer.data)

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):

        order_data = request.data

        new_order = Order.objects.create(owner=request.user, product=order_data['product'], quantity=order_data['quantity'])

        new_order.save()

        serializer = OrderSerializer(new_order)

        headers = CreateModelMixin.get_success_headers(self, serializer.data)

        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "home.html"

users/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'pages:home' %}">Django Rest API</a>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">Sign Out</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <!-- Jquery masks -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Django Rest API{% endblock %}

{% block content %}
    {% if user.is_authenticated %}
        {% if user.is_staff %}
        <details>
            <summary>Admin Panel</summary>
                <ul>
                    <li>You can access admin panel <a href="{% url 'admin:index' %}">here</a>.</li>
                </ul>
        </details>
        {% endif %}
        <details>
            <summary>Order Api Actions</summary>
                <ul>
                    <li>Add orders <a href="{% url 'order-list' %}">here</a>.</li>
                    <li>Delete orders <a href="{% url 'order-delete' pk=1 %}">here</a>.</li>
                    <li>Update orders <a href="{% url 'order-update' pk=1 %}">here</a>.</li>
                </ul>
        </details>
    {% endif %}
{% endblock %}